apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../app

namespace: billo-prod

patches:
  - target:
      kind: Deployment
      name: billo-ui
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Ingress
      name: billo-ui
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: app.billo.com
      - op: replace
        path: /spec/rules/0/host
        value: app.billo.com
  - target:
      kind: Deployment
      name: billo-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Ingress
      name: billo-api
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api.billo.com
      - op: replace
        path: /spec/rules/0/host
        value: api.billo.com

configMapGenerator:
  - name: billo-backend-config
    behavior: merge
    literals:
      - BILLO_FRONTEND_URL="https://app.billo.com"
      - BILLO_API_URL="https://api.billo.com"
      - BILLO_DB_NAME="billo_db"
      - BILLO_DB_HOST="<vps_ip>"
      - BILLO_MINIO_HOST="<object-storage-host>"
      - BILLO_MINIO_PORT=""
      - BILLO_MINIO_BUCKET="billo"
      - BILLO_MINIO_SECURE="True"

secretGenerator:
  - name: billo-backend-secrets
    literals:
      - BILLO_SECRET_KEY=${BILLO_SECRET_KEY}
      - BILLO_FERNET_SECRET_KEY=${BILLO_FERNET_SECRET_KEY}
      - BILLO_DB_USER=${BILLO_DB_USER}
      - BILLO_DB_PASSWORD=${BILLO_DB_PASSWORD}
      - BILLO_MAIL_SERVER=${BILLO_MAIL_SERVER}
      - BILLO_MAIL_USERNAME=${BILLO_MAIL_USERNAME}
      - BILLO_MAIL_PASSWORD=${BILLO_MAIL_PASSWORD}
      - BILLO_MAIL_DEFAULT_SENDER=${BILLO_MAIL_DEFAULT_SENDER}
      - BILLO_MOLLIE_API_KEY=${BILLO_MOLLIE_API_KEY}
      - BILLO_MINIO_USER=${BILLO_MINIO_USER}
      - BILLO_MINIO_PASSWORD=${BILLO_MINIO_PASSWORD}
