apiVersion: apps/v1
kind: Deployment
metadata:
  name: billo-tasks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billo-tasks
  template:
    metadata:
      labels:
        app: billo-tasks
    spec:
      imagePullSecrets:
        - name: billo-dockerhub
      containers:
        - name: billo-tasks
          image: bramdewit/billo-tasks
          envFrom:
            - configMapRef:
                name: billo-backend-config
            - secretRef:
                name: billo-backend-secrets
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
