FROM python:3.13

RUN apt-get update && apt-get -y upgrade && apt-get install -y --no-install-recommends ffmpeg

RUN useradd --create-home billo
USER billo

WORKDIR /home/billo

RUN python -m venv venv
ENV PATH="/home/billo/venv/bin:$PATH"

COPY --chown=billo requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY --chown=billo . .

# Run Celery worker
CMD ["celery", "--app=server.celery_app", "worker", "--loglevel=info"]
