FROM python:3.13

RUN useradd --create-home billo
USER billo

WORKDIR /home/billo

RUN python -m venv venv
ENV PATH="/home/billo/venv/bin:$PATH"

COPY --chown=billo requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY --chown=billo . .

EXPOSE 5000

CMD ["gunicorn", "--log-level", "debug", "-w", "4", "-b", "0.0.0.0:5000", "server:app"]
