name: Deploy prod

on:
  push:
    tags:
      - "v[0-9].[0-9]+.[0-9]+"

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.vars.outputs.tag_name }}
    steps:
      - name: Setup
        uses: actions/checkout@v4

      - name: Get Tag Name
        id: vars
        run: echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push UI (Prod)
        run: |
          cd ui && make \
            DOCKERHUB_NAMESPACE=${{ secrets.DOCKERHUB_NAMESPACE }} \
            IMAGE_TAG=${{ steps.vars.outputs.tag_name }} \
            VITE_APP_VERSION=${{ steps.vars.outputs.tag_name }} \
            VITE_API_BASE_URL=https://api.billo.com \
            docker_build docker_push

      - name: Build & Push API/Tasks (Prod)
        run: |
          cd api && make \
            DOCKERHUB_NAMESPACE=${{ secrets.DOCKERHUB_NAMESPACE }} \
            IMAGE_TAG=${{ steps.vars.outputs.tag_name }} \
            docker_build_api docker_push_api \
            docker_build_tasks docker_push_tasks

  deploy-prod:
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    env:
      NAMESPACE: billo-prod
      TAG: ${{ needs.docker-build-and-push.outputs.tag_name }}
    steps:
      - name: Setup
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_PROD }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Create Dockerhub Secret
        run: |
          kubectl create secret docker-registry billo-dockerhub \
            --docker-username=${{ secrets.DOCKERHUB_USERNAME }} \
            --docker-password=${{ secrets.DOCKERHUB_TOKEN }} \
            --docker-email="<your-email>" \
            -n ${NAMESPACE} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to prod
        env:
          BILLO_SECRET_KEY: ${{ secrets.BILLO_SECRET_KEY }}
          BILLO_FERNET_SECRET_KEY: ${{ secrets.BILLO_FERNET_SECRET_KEY }}
          BILLO_DB_USER: ${{ secrets.BILLO_DB_USER }}
          BILLO_DB_PASSWORD: ${{ secrets.BILLO_DB_PASSWORD }}
          BILLO_MAIL_SERVER: ${{ secrets.BILLO_MAIL_SERVER }}
          BILLO_MAIL_USERNAME: ${{ secrets.BILLO_MAIL_USERNAME }}
          BILLO_MAIL_PASSWORD: ${{ secrets.BILLO_MAIL_PASSWORD }}
          BILLO_MAIL_DEFAULT_SENDER: ${{ secrets.BILLO_MAIL_DEFAULT_SENDER }}
        run: |
          cd config/k8s/overlays/prod

          envsubst < kustomization.yaml > kustomization.tmp.yaml
          mv kustomization.tmp.yaml kustomization.yaml

          kustomize edit set image bramdewit/billo-api=bramdewit/billo-api:${{ env.TAG }}
          kustomize edit set image bramdewit/billo-tasks=bramdewit/billo-tasks:${{ env.TAG }}
          kustomize edit set image bramdewit/billo-ui=bramdewit/billo-ui:${{ env.TAG }}

          kubectl apply -k .

      - name: Verify rollouts
        run: |
          kubectl rollout status deployment/billo-ui -n ${NAMESPACE}
          kubectl rollout status deployment/billo-api -n ${NAMESPACE}
          kubectl rollout status deployment/billo-tasks -n ${NAMESPACE}

      - name: Run DB migrations
        run: |
          kubectl exec deploy/billo-api -n ${NAMESPACE} -- make db_upgrade
