name: Deploy staging

on:
  push:
    branches:
      - develop

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    steps:
      - name: Setup
        uses: actions/checkout@v4

      - name: Set SHA output
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push UI
        run: |
          cd ui && make \
            DOCKERHUB_NAMESPACE=${{ secrets.DOCKERHUB_NAMESPACE }} \
            IMAGE_TAG=${{ steps.vars.outputs.sha_short }} \
            VITE_APP_VERSION=${{ steps.vars.outputs.sha_short }} \
            VITE_API_BASE_URL=https://staging.api.billo.com \
            docker_build docker_push

      - name: Build & Push API/Tasks
        run: |
          cd api && make \
            DOCKERHUB_NAMESPACE=${{ secrets.DOCKERHUB_NAMESPACE }} \
            IMAGE_TAG=${{ steps.vars.outputs.sha_short }} \
            docker_build_api docker_push_api \
            docker_build_tasks docker_push_tasks

  deploy-staging:
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    env:
      NAMESPACE: billo-staging
      SHA: ${{ needs.docker-build-and-push.outputs.sha_short }}
    steps:
      - name: Setup
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_STAGING }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Create Dockerhub Secret
        run: |
          kubectl create secret docker-registry billo-dockerhub \
            --docker-username=${{ secrets.DOCKERHUB_USERNAME }} \
            --docker-password=${{ secrets.DOCKERHUB_TOKEN }} \
            --docker-email="<your-email>" \
            -n ${NAMESPACE} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to staging
        env:
          BILLO_SECRET_KEY: ${{ secrets.BILLO_STAGING_SECRET_KEY }}
          BILLO_FERNET_SECRET_KEY: ${{ secrets.BILLO_STAGING_FERNET_SECRET_KEY }}
          BILLO_DB_USER: ${{ secrets.BILLO_STAGING_DB_USER }}
          BILLO_DB_PASSWORD: ${{ secrets.BILLO_STAGING_DB_PASSWORD }}
          BILLO_MAIL_SERVER: ${{ secrets.BILLO_STAGING_MAIL_SERVER }}
          BILLO_MAIL_USERNAME: ${{ secrets.BILLO_STAGING_MAIL_USERNAME }}
          BILLO_MAIL_PASSWORD: ${{ secrets.BILLO_STAGING_MAIL_PASSWORD }}
          BILLO_MAIL_DEFAULT_SENDER: ${{ secrets.BILLO_STAGING_MAIL_DEFAULT_SENDER }}
        run: |
          cd config/k8s/overlays/staging

          envsubst < kustomization.yaml > kustomization.tmp.yaml
          mv kustomization.tmp.yaml kustomization.yaml

          kustomize edit set image bramdewit/billo-api=bramdewit/billo-api:${{ env.SHA }}
          kustomize edit set image bramdewit/billo-tasks=bramdewit/billo-tasks:${{ env.SHA }}
          kustomize edit set image bramdewit/billo-ui=bramdewit/billo-ui:${{ env.SHA }}

          kubectl apply -k .

      - name: Verify rollouts
        run: |
          kubectl rollout status deployment/billo-ui -n ${NAMESPACE}
          kubectl rollout status deployment/billo-api -n ${NAMESPACE}
          kubectl rollout status deployment/billo-tasks -n ${NAMESPACE}

      - name: Run DB migrations
        run: |
          kubectl exec deploy/billo-api -n ${NAMESPACE} -- make db_upgrade
